version: '3.7'

networks:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: dungeon_nginx
    restart: unless-stopped
    ports:
      - "5505:80"
    volumes:
      - ./:/opt/app
      - ./.docker/nginx:/etc/nginx/conf.d
      - /var/logs/dungeon_wallet/nginx:/var/log/nginx/
    depends_on:
      - php
      - postgres
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: dungeon_redis
    restart: unless-stopped
    ports:
      - "22545:6379"
    volumes:
      - /var/data/dungeon_wallet/redis/data:/var/lib/redis
      - ./.docker/redis/redis/conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  postgres:
    image: postgres:alpine
    container_name: dungeon_postgres
    restart: unless-stopped
    volumes:
      - /var/data/dungeon_wallet/database:/var/lib/postgresql/data
      - /var/data/dungeon_wallet/dump:/dump
    ports:
      - "54327:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
        - backend

  php:
    build:
      context: ./.docker/php
      args:
        DOCKER_PHP_VERSION: '8.0'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /opt/app
    restart: unless-stopped
    command: sh -c "/usr/local/sbin/php-fpm"
    user: www-data
    container_name: dungeon_php
    volumes:
      - ./:/opt/app
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
    networks:
      - backend

